#!/bin/sh

__koopa_activate_user_profile() {
    # """
    # Activate koopa shell for current user.
    # @note Updated 2023-05-12.
    # @seealso 
    # - https://koopa.acidgenomics.com/
    # - https://github.com/acidgenomics/koopa/
    # """
    __kvar_xdg_config_home="${XDG_CONFIG_HOME:-}"
    if [ -z "$__kvar_xdg_config_home" ]
    then
        __kvar_xdg_config_home="${HOME:?}/.config"
    fi
    __kvar_script="${__kvar_xdg_config_home}/koopa/activate"
    if [ -r "$__kvar_script" ]
    then
        # shellcheck source=/dev/null
        . "$__kvar_script"
    fi
    unset -v __kvar_script __kvar_xdg_config_home
    return 0
}

__koopa_activate_user_profile
