#!/usr/bin/env bash

# FIXME Early return for super old bash versions.

__dotfiles_bashrc() {
    [[ "$-" == *i* ]] || return 0
    [[ -f "${HOME}/.profile" ]] || return 0
    # shellcheck source=/dev/null
    source "${HOME}/.profile"
    return 0
}

__dotfiles_bashrc
