#!/usr/bin/env bash

__dotfiles_bashrc() {
    case "${BASH_VERSION:-}" in
        '1.'* | '2.'* | '3.'*)
            return 0
            ;;
    esac
    [[ "$-" == *i* ]] || return 0
    [[ -f "${HOME}/.profile" ]] || return 0
    # shellcheck source=/dev/null
    source "${HOME}/.profile"
    return 0
}

__dotfiles_bashrc
