#!/usr/bin/env zsh

# """
# ZSH environment configuration.
# @note Updated 2023-03-27.
# """

# This is the current default configuration.
# > export ZDOTDIR="${HOME:?}"

# Alternative configuration in '~/.config/zsh'.
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME:?}/.config}"
export ZDOTDIR="${ZDOTDIR:-${XDG_CONFIG_HOME}/zsh}"

