#!/usr/bin/env zsh

# """
# ZSH environment configuration.
# @note Updated 2025-01-03.
#
# @seealso
# - https://unix.stackexchange.com/questions/72559/
# """

# This is the current default configuration.
# > export ZDOTDIR="${HOME:?}"

# Alternative configuration in '~/.config/zsh'.
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME:?}/.config}"
export ZDOTDIR="${ZDOTDIR:-${XDG_CONFIG_HOME}/zsh}"

# Avoid parsing system /etc files. When GLOBAL_RCS is unset, /etc/zprofile,
# /etc/zshrc, /etc/zlogin and /etc/zlogout will not be sourced.
unsetopt GLOBAL_RCS
