#!/bin/sh

# """
# POSIX shell profile configuration.
# Used for Bash and Zsh shell configuration.
#
# Git repo:
# https://github.com/acidgenomics/dotfiles/
# """

__koopa_activate_user_profile() {
    # """
    # Activate koopa shell for current user.
    #
    # See also:
    # - https://koopa.acidgenomics.com/
    # - https://github.com/acidgenomics/koopa/
    # """
    __kvar_xdg_data_home="${XDG_DATA_HOME:-}"
    if [ -z "$__kvar_xdg_data_home" ]
    then
        __kvar_xdg_data_home="${HOME:?}/.local/share"
    fi
    __kvar_script="${__kvar_xdg_data_home}/koopa/activate.sh"
    if [ -r "$__kvar_script" ]
    then
        # shellcheck source=/dev/null
        . "$__kvar_script"
    fi
    unset -v __kvar_script __kvar_xdg_data_home
    return 0
}

__koopa_activate_user_profile
