(("default" . ((user-emacs-directory . "~/.local/share/doom")))
 ("doom" . ((user-emacs-directory . "~/.local/share/doom")))
 ("minimal" . ((user-emacs-directory . "~/.config/koopa/dotfiles/app/emacs")))
 ("prelude" . ((user-emacs-directory . "~/.local/share/prelude")))
 ("spacemacs" . ((user-emacs-directory . "~/.local/share/spacemacs"))))
