#!/usr/bin/env python3

"""Python interactive startup configuration.

See Also
--------
- https://stackoverflow.com/questions/33683744
- https://www.codementor.io/@arpitbhayani/
      personalize-your-python-prompt-13ts4kw6za
"""

import sys

if sys.version_info >= (3, 13): # noqa UP036
    sys.ps1 = '\x1b[1;49;35m>>>\x1b[0m '
    sys.ps2 = '\x1b[1;49;31m...\x1b[0m '
