#!/usr/bin/env bash

# """
# Bash shell configuration.
# Refer to '~/.profile' file for POSIX shell configuration details.
# """

__dotfiles_bash_profile() {
    case "${BASH_VERSION:-}" in
        '1.'* | '2.'* | '3.'*)
            return 0
            ;;
    esac
    [[ "$-" == *i* ]] || return 0
    if [[ -f "${HOME}/.profile" ]]
    then
        # shellcheck source=/dev/null
        source "${HOME}/.profile"
    fi
    return 0
}

__dotfiles_bash_profile
