# """
# lsd configuration.
# @note Updated 2023-09-07.
#
# @seealso
# - https://github.com/lsd-rs/lsd#config-file-content
# - https://github.com/lsd-rs/lsd#color-theme-file-content
# - https://github.com/sharkdp/vivid/
# """

classic: false
color:
  when: "never"
  theme: "no-color"
