# """
# One Light scheme.
# @note Updated 2024-01-02.
#
# @seealso
# - https://github.com/aarowill/base16-alacritty/blob/master/
#     colors/base16-one-light.toml
# - https://github.com/alacritty/alacritty-theme/blob/master/
#     themes/atom_one_light.toml
# """

[colors.bright]
black = "#a0a1a7"
blue = "#696c77"
cyan = "#986801"
green = "#f0f0f1"
magenta = "#202227"
red = "#d75f00"
white = "#090a0b"
yellow = "#e5e5e6"

[colors.normal]
black = "#fafafa"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
white = "#383a42"
yellow = "#c18401"

[colors.primary]
background = "#fafafa"
foreground = "#383a42"
